platform :ios, '13.0'

target 'PokedexGo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift',    '~> 6.5.0'
  pod 'RxCocoa',    '~> 6.5.0'

end
